[workspace]
members = [
  "snake_game",
  "snake_game_full_wasm",
  "snake_game_full_wasm_glsl",
  "game_utils",
  "repo_tools",
]

[profile.release]
# Tell `rustc` to optimize for small code size.
opt-level = "s"
